### ISSUE TITLE
TypeError: Cannot assign to read only property 'prepareStatusEl' of object '#<BrowserTransport>'

### ISSUE THREAD

**Issue by Gelurban** [greymass/anchor-link-browser-transport#17]
Hello. I'm having trouble setting up anchor-link on a React + Typescript app.
I'm using the same code in a Vue app, and everything is working fine.

I'm able to login and the the user's session, however when I try to use the transact function, I'm getting this error:

```
Uncaught (in promise) TypeError: Cannot assign to read only property 'prepareStatusEl' of object '#<BrowserTransport>'
    at BrowserTransport.showLoading (app.js:9870:30)
    at LinkChannelSession.showLoading (app.js:10784:40)
    at Link.transact (app.js:11298:15)
    at LinkChannelSession.transact (app.js:10797:37)
    at app.js:31552:24
    at step (app.js:31363:19)
    at Object.next (app.js:31293:14)
    at app.js:31265:67
    at new Promise (<anonymous>)
    at __webpack_modules__../resources/js/Domains/Wallet/useWallet.ts.__awaiter (app.js:31244:10)
```
It references the line 366 of anchor-link-browser-transport's index.ts

[https://github.com/greymass/anchor-link-browser-transport/blob/936d07836ce749539aa6e50d5429980af75c6c79/src/index.ts#L366](https://github.com/greymass/anchor-link-browser-transport/blob/936d07836ce749539aa6e50d5429980af75c6c79/src/index.ts#L366)

Thanks in advance

**Comment by aaroncox** [comment]
Could it be something to do with how it's being packaged, or is the transport or link getting passed into some sort of state that's altering it? 

I'm not entirely sure what's going on. Any chance you have a reproducible code sample?
